# Generated by Django 2.2.9 on 2020-01-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_auto_20200103_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
    ]
